version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: todo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - todo-network

  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb+srv://<username>:<password>@todo-cluster.jamzgna.mongodb.net
      - JWT_SECRET=not-an-option
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - todo-network

  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mongodb_data: